// AUTO-ÜRETİLDİ — ürün bazlı SEO varsayılanları (113 ürün).
// Üretim: çekişmeli-fact-check workflow (geçici scriptler, repo'da tutulmaz). Bu dosya,
// ürünün Blob'unda/admin'inde SEO alanı BOŞSA devreye giren varsayılandır; admin'de
// doldurulan değer DAİMA kazanır (applyProductSeo `pick` ile override eder).
// Kaynak veri admin panelinden ürün başına düzenlenebilir.

export type ProductSeo = {
  metaTitle?: string;
  metaDescription?: string;
  focusKeyword?: string;
  keywords?: string;
};

export const PRODUCT_SEO: Record<string, ProductSeo> = {
  "charger-2-kablolu": {"metaTitle":"AC Wallbox Charger 2 — 5m Kablolu Type 2","metaDescription":"AC wallbox şarj istasyonu Charger 2; 7,4–22 kW, 5m entegre Type 2 kablo, yerli üretim · CE · IP65. Ev ve iş yeri için güvenli. Üreticisinden teklif alın.","focusKeyword":"ac wallbox şarj istasyonu","keywords":"ac wallbox şarj istasyonu, charger 2, type 2 kablolu wallbox, duvar tipi ev şarj cihazı, yerli ev şarj istasyonu, bemis ev charge, 22 kw ac şarj"},
  "charger-2-fisli": {"metaTitle":"AC Wallbox Charger 2 — 5-32A Fişli Type 2","metaDescription":"AC wallbox şarj istasyonu Charger 2 fişli; 7,4–22 kW, 32A priz/Type 2 kablo seçeneği, yerli üretim · CE · IP65. Ev ve iş yeri için. Üreticisinden teklif alın.","focusKeyword":"ac wallbox şarj istasyonu fişli","keywords":"ac wallbox şarj istasyonu, charger 2 fişli, 32a fişli wallbox, type 2 duvar tipi şarj, yerli ev şarj cihazı, bemis ev charge, 22 kw ac şarj"},
  "charger-plus-2-kablolu": {"metaTitle":"AC Wallbox Charger Plus 2 — Ayarlanabilir Güç","metaDescription":"AC wallbox şarj istasyonu Charger Plus 2; 4–22 kW ayarlanabilir güç, akıllı şarj, 5m Type 2 kablo, yerli üretim · CE · IP65. Üreticisinden teklif alın.","focusKeyword":"ac wallbox şarj istasyonu ayarlanabilir","keywords":"ac wallbox şarj istasyonu, charger plus 2, ayarlanabilir güç wallbox, akıllı ev şarj cihazı, type 2 duvar tipi şarj, yerli ev şarj istasyonu, bemis ev charge"},
  "charger-plus-2-pano": {"metaTitle":"AC Wallbox Charger Plus 2 — Pano Prizli","metaDescription":"AC wallbox şarj istasyonu Charger Plus 2 pano prizli; 4–22 kW ayarlanabilir güç, akıllı şarj, yerli üretim · CE · IP65. Ev ve işletme için. Üreticisinden teklif alın.","focusKeyword":"ac wallbox şarj istasyonu pano prizli","keywords":"ac wallbox şarj istasyonu, charger plus 2 pano, pano prizli wallbox, ayarlanabilir güç ev şarj, type 2 duvar tipi şarj, yerli ev şarj cihazı, bemis ev charge"},
  "charger-pro-2-kablolu": {"metaTitle":"AC Wallbox Charger Pro 2 — OCPP 1.6 DLM","metaDescription":"AC wallbox şarj istasyonu Charger Pro 2; 4–22 kW, OCPP 1.6, yük yönetimi (DLM), 5m Type 2 kablo, yerli üretim · CE · IP65. Üreticisinden teklif alın.","focusKeyword":"ocpp ac wallbox şarj istasyonu","keywords":"ac wallbox şarj istasyonu, charger pro 2, ocpp wallbox, dlm yük yönetimi şarj, type 2 duvar tipi şarj, yerli ev şarj cihazı, bemis ev charge"},
  "charger-pro-2-pano": {"metaTitle":"AC Wallbox Charger Pro 2 — Pano Prizli OCPP","metaDescription":"AC wallbox şarj istasyonu Charger Pro 2 pano prizli; 4–22 kW, OCPP 1.6, yük yönetimi (DLM), yerli üretim · CE · IP65. Operatörlere uygun. Üreticisinden teklif alın.","focusKeyword":"ocpp ac wallbox şarj istasyonu pano prizli","keywords":"ac wallbox şarj istasyonu, charger pro 2 pano, pano prizli ocpp wallbox, dlm yük yönetimi şarj, type 2 duvar tipi şarj, yerli ev şarj cihazı, bemis ev charge"},
  "charger-pro-2-gsm-pano": {"metaTitle":"AC Wallbox Charger Pro 2 GSM — 4G Pano Prizli","metaDescription":"AC wallbox şarj istasyonu Charger Pro 2 GSM; dahili 4G ile uzaktan izleme, OCPP 1.6, pano prizli, yerli üretim · CE · IP65. Saha kurulumuna uygun. Üreticisinden teklif alın.","focusKeyword":"gsm ac wallbox şarj istasyonu pano prizli","keywords":"ac wallbox şarj istasyonu, charger pro 2 gsm, 4g gsm wallbox, uzaktan izleme şarj istasyonu, ocpp pano prizli wallbox, yerli ev şarj cihazı, bemis ev charge"},
  "charger-pro-2-gsm-kablolu": {"metaTitle":"AC Wallbox Charger Pro 2 GSM — 4G Type 2 Kablolu","metaDescription":"AC wallbox şarj istasyonu Charger Pro 2 GSM; dahili 4G ile uzaktan izleme, OCPP 1.6, 5m Type 2 kablo, yerli üretim · CE · IP65. Saha kurulumuna uygun. Üreticisinden teklif alın.","focusKeyword":"gsm ac wallbox şarj istasyonu kablolu","keywords":"ac wallbox şarj istasyonu, charger pro 2 gsm, 4g gsm wallbox, uzaktan izleme şarj istasyonu, type 2 kablolu ocpp wallbox, yerli ev şarj cihazı, bemis ev charge"},
  "mini-mobile": {"metaTitle":"Taşınabilir Şarj Cihazı Mini Mobile 3,7 kW","metaDescription":"Taşınabilir elektrikli araç şarj cihazı Mini Mobile: 2,3-3,7 kW monofaze, Schuko prize takılır, çantalı. Yerli üretim · CE · IP65. Üreticisinden teklif alın.","focusKeyword":"taşınabilir şarj cihazı mini mobile","keywords":"taşınabilir şarj cihazı, mini mobile şarj cihazı, schuko taşınabilir ev şarj, monofaze taşınabilir şarj, seyahat ev şarj cihazı, yerli, bemis"},
  "mono-mobile": {"metaTitle":"Taşınabilir Şarj Cihazı Mono Mobile 7,4 kW","metaDescription":"Taşınabilir elektrikli araç şarj cihazı Mono Mobile: 3,7-7,4 kW monofaze, CEE 16/32A ve Schuko adaptörlü. Yerli üretim · CE · IP65. Üreticisinden teklif alın.","focusKeyword":"taşınabilir şarj cihazı mono mobile","keywords":"taşınabilir şarj cihazı, mono mobile şarj cihazı, cee adaptörlü taşınabilir şarj, monofaze taşınabilir ev şarj, mobil ev şarj cihazı, yerli, bemis"},
  "pro-mobile": {"metaTitle":"Taşınabilir Şarj Cihazı Pro Mobile 2 · 22 kW","metaDescription":"Taşınabilir elektrikli araç şarj cihazı Pro Mobile 2: 11-22 kW trifaze, 6 kademe amper ayarı (6-32A), CEE 5/16A ve 5/32A adaptörlü saha şarjı. Yerli üretim · CE · IP65. Üreticisinden teklif alın.","focusKeyword":"taşınabilir şarj cihazı pro mobile","keywords":"taşınabilir şarj cihazı, pro mobile 2 şarj cihazı, pro mobile şarj cihazı, trifaze taşınabilir şarj, 22 kw taşınabilir ev şarj, filo saha şarj cihazı, yerli, bemis"},
  "sarj-seti-20a-monofaze-3m": {"metaTitle":"Type 2 Şarj Kablosu 16A Monofaze 3m – 3,7 kW","metaDescription":"Type 2 EV şarj kablosu 16A monofaze 3m, 3,7 kW Mod 3 şarj seti; halojensiz kablo, yerli üretim · CE · IP65. Ev tipi priz ve AC wallbox uyumlu. Üreticisinden teklif alın.","focusKeyword":"type 2 şarj kablosu 16a","keywords":"type 2 şarj kablosu 16a, ev şarj kablosu monofaze, 3,7 kw mod 3 şarj seti, elektrikli araç şarj kablosu, yerli ev şarj kablosu, bemis type 2 kablo, wallbox şarj kablosu"},
  "sarj-seti-20a-monofaze-5m": {"metaTitle":"Type 2 Şarj Kablosu 16A Monofaze 5m – 3,7 kW","metaDescription":"Type 2 EV şarj kablosu 16A monofaze 5m, 3,7 kW Mod 3 şarj seti; halojensiz kablo, yerli üretim · CE · IP65. Ev tipi priz ve AC wallbox uyumlu. Üreticisinden teklif alın.","focusKeyword":"type 2 şarj kablosu 16a 5m","keywords":"type 2 şarj kablosu 16a, ev şarj kablosu monofaze, 5m şarj kablosu, 3,7 kw mod 3 şarj seti, elektrikli araç şarj kablosu, yerli ev şarj kablosu, bemis type 2 kablo"},
  "sarj-seti-20a-monofaze-7m": {"metaTitle":"Type 2 Şarj Kablosu 16A Monofaze 7m – 3,7 kW","metaDescription":"Type 2 EV şarj kablosu 16A monofaze 7m, 3,7 kW Mod 3 şarj seti; halojensiz kablo, yerli üretim · CE · IP65. Ev tipi priz ve AC wallbox uyumlu. Üreticisinden teklif alın.","focusKeyword":"type 2 şarj kablosu 16a 7m","keywords":"type 2 şarj kablosu 16a, ev şarj kablosu monofaze, 7m şarj kablosu, 3,7 kw mod 3 şarj seti, elektrikli araç şarj kablosu, yerli ev şarj kablosu, bemis type 2 kablo"},
  "sarj-seti-20a-monofaze-8m": {"metaTitle":"Type 2 Şarj Kablosu 16A Monofaze 8m – 3,7 kW","metaDescription":"Type 2 EV şarj kablosu 16A monofaze 8m, 3,7 kW Mod 3 şarj seti; halojensiz kablo, yerli üretim · CE · IP65. Ev tipi priz ve AC wallbox uyumlu. Üreticisinden teklif alın.","focusKeyword":"type 2 şarj kablosu 16a 8m","keywords":"type 2 şarj kablosu 16a, ev şarj kablosu monofaze, 8m şarj kablosu, 3,7 kw mod 3 şarj seti, elektrikli araç şarj kablosu, yerli ev şarj kablosu, bemis type 2 kablo"},
  "sarj-seti-20a-monofaze-10m": {"metaTitle":"Type 2 Şarj Kablosu 16A Monofaze 10m – 3,7 kW","metaDescription":"Type 2 EV şarj kablosu 16A monofaze 10m, 3,7 kW Mod 3 şarj seti; halojensiz kablo, yerli üretim · CE · IP65. Ev tipi priz ve AC wallbox uyumlu. Üreticisinden teklif alın.","focusKeyword":"type 2 şarj kablosu 16a 10m","keywords":"type 2 şarj kablosu 16a, ev şarj kablosu monofaze, 10m şarj kablosu, 3,7 kw mod 3 şarj seti, elektrikli araç şarj kablosu, yerli ev şarj kablosu, bemis type 2 kablo"},
  "sarj-seti-32a-monofaze-3m": {"metaTitle":"Type 2 Şarj Kablosu 32A Monofaze 3m – 7,4 kW","metaDescription":"Type 2 EV şarj kablosu 32A monofaze 3m, 7,4 kW Mod 3 şarj seti; halojensiz kablo, yerli üretim · CE · IP65. Ev ve iş yeri AC wallbox için optimize. Üreticisinden teklif alın.","focusKeyword":"type 2 şarj kablosu 32a","keywords":"type 2 şarj kablosu 32a, ev şarj kablosu monofaze, 7,4 kw mod 3 şarj seti, elektrikli araç şarj kablosu, yerli ev şarj kablosu, bemis type 2 kablo, wallbox şarj kablosu"},
  "sarj-seti-32a-monofaze-5m": {"metaTitle":"Type 2 Şarj Kablosu 32A Monofaze 5m – 7,4 kW","metaDescription":"Type 2 EV şarj kablosu 32A monofaze 5m, 7,4 kW Mod 3 şarj seti; halojensiz kablo, yerli üretim · CE · IP65. Ev ve iş yeri AC wallbox için optimize. Üreticisinden teklif alın.","focusKeyword":"type 2 şarj kablosu 32a 5m","keywords":"type 2 şarj kablosu 32a, ev şarj kablosu monofaze, 5m şarj kablosu, 7,4 kw mod 3 şarj seti, elektrikli araç şarj kablosu, yerli ev şarj kablosu, bemis type 2 kablo"},
  "sarj-seti-32a-monofaze-7m": {"metaTitle":"Type 2 Şarj Kablosu 32A Monofaze 7m – 7,4 kW","metaDescription":"Type 2 EV şarj kablosu 32A monofaze 7m, 7,4 kW Mod 3 şarj seti; halojensiz kablo, yerli üretim · CE · IP65. Ev ve iş yeri AC wallbox için optimize. Üreticisinden teklif alın.","focusKeyword":"type 2 şarj kablosu 32a 7m","keywords":"type 2 şarj kablosu 32a, ev şarj kablosu monofaze, 7m şarj kablosu, 7,4 kw mod 3 şarj seti, elektrikli araç şarj kablosu, yerli ev şarj kablosu, bemis type 2 kablo"},
  "sarj-seti-32a-monofaze-8m": {"metaTitle":"Type 2 Şarj Kablosu 32A Monofaze 8m – 7,4 kW","metaDescription":"Type 2 EV şarj kablosu 32A monofaze 8m, 7,4 kW Mod 3 şarj seti; halojensiz kablo, yerli üretim · CE · IP65. Ev ve iş yeri AC wallbox için optimize. Üreticisinden teklif alın.","focusKeyword":"type 2 şarj kablosu 32a 8m","keywords":"type 2 şarj kablosu 32a, ev şarj kablosu monofaze, 8m şarj kablosu, 7,4 kw mod 3 şarj seti, elektrikli araç şarj kablosu, yerli ev şarj kablosu, bemis type 2 kablo"},
  "sarj-seti-32a-monofaze-10m": {"metaTitle":"Type 2 Şarj Kablosu 32A Monofaze 10m – 7,4 kW","metaDescription":"Type 2 EV şarj kablosu 32A monofaze 10m, 7,4 kW Mod 3 şarj seti; halojensiz kablo, yerli üretim · CE · IP65. Ev ve iş yeri AC wallbox için optimize. Üreticisinden teklif alın.","focusKeyword":"type 2 şarj kablosu 32a 10m","keywords":"type 2 şarj kablosu 32a, ev şarj kablosu monofaze, 10m şarj kablosu, 7,4 kw mod 3 şarj seti, elektrikli araç şarj kablosu, yerli ev şarj kablosu, bemis type 2 kablo"},
  "sarj-seti-20a-trifaze-3m": {"metaTitle":"Type 2 Şarj Kablosu 16A Trifaze 3m – 11 kW","metaDescription":"Type 2 EV şarj kablosu 16A trifaze 3m, 11 kW Mod 3 şarj seti; halojensiz kablo, yerli üretim · CE · IP65. Ticari ve iş yeri uygulamaları için. Üreticisinden teklif alın.","focusKeyword":"type 2 şarj kablosu 16a trifaze","keywords":"type 2 şarj kablosu 16a trifaze, ev şarj kablosu trifaze, 11 kw mod 3 şarj seti, elektrikli araç şarj kablosu, yerli ev şarj kablosu, bemis type 2 kablo, ticari şarj kablosu"},
  "sarj-seti-20a-trifaze-5m": {"metaTitle":"Type 2 Şarj Kablosu 16A Trifaze 5m – 11 kW","metaDescription":"Type 2 EV şarj kablosu 16A trifaze 5m, 11 kW Mod 3 şarj seti; halojensiz kablo, yerli üretim · CE · IP65. Ticari ve iş yeri uygulamaları için. Üreticisinden teklif alın.","focusKeyword":"type 2 şarj kablosu 16a trifaze 5m","keywords":"type 2 şarj kablosu 16a trifaze, ev şarj kablosu trifaze, 5m şarj kablosu, 11 kw mod 3 şarj seti, elektrikli araç şarj kablosu, yerli ev şarj kablosu, bemis type 2 kablo"},
  "sarj-seti-20a-trifaze-7m": {"metaTitle":"Type 2 Şarj Kablosu 16A Trifaze 7m – 11 kW","metaDescription":"Type 2 EV şarj kablosu 16A trifaze 7m, 11 kW Mod 3 şarj seti; halojensiz kablo, yerli üretim · CE · IP65. Ticari ve iş yeri uygulamaları için. Üreticisinden teklif alın.","focusKeyword":"type 2 şarj kablosu 16a trifaze 7m","keywords":"type 2 şarj kablosu 16a trifaze, ev şarj kablosu trifaze, 7m şarj kablosu, 11 kw mod 3 şarj seti, elektrikli araç şarj kablosu, yerli ev şarj kablosu, bemis type 2 kablo"},
  "sarj-seti-20a-trifaze-8m": {"metaTitle":"Type 2 Şarj Kablosu 16A Trifaze 8m – 11 kW","metaDescription":"Type 2 EV şarj kablosu 16A trifaze 8m, 11 kW Mod 3 şarj seti; halojensiz kablo, yerli üretim · CE · IP65. Ticari ve iş yeri uygulamaları için. Üreticisinden teklif alın.","focusKeyword":"type 2 şarj kablosu 16a trifaze 8m","keywords":"type 2 şarj kablosu 16a trifaze, ev şarj kablosu trifaze, 8m şarj kablosu, 11 kw mod 3 şarj seti, elektrikli araç şarj kablosu, yerli ev şarj kablosu, bemis type 2 kablo"},
  "sarj-seti-20a-trifaze-10m": {"metaTitle":"Type 2 Şarj Kablosu 16A Trifaze 10m – 11 kW","metaDescription":"Type 2 EV şarj kablosu 16A trifaze 10m, 11 kW Mod 3 şarj seti; halojensiz kablo, yerli üretim · CE · IP65. Ticari ve iş yeri uygulamaları için. Üreticisinden teklif alın.","focusKeyword":"type 2 şarj kablosu 16a trifaze 10m","keywords":"type 2 şarj kablosu 16a trifaze, ev şarj kablosu trifaze, 10m şarj kablosu, 11 kw mod 3 şarj seti, elektrikli araç şarj kablosu, yerli ev şarj kablosu, bemis type 2 kablo"},
  "sarj-seti-20a-trifaze-15m": {"metaTitle":"Type 2 Şarj Kablosu 16A Trifaze 15m – 11 kW","metaDescription":"Type 2 EV şarj kablosu 16A trifaze 15m, 11 kW Mod 3 şarj seti; halojensiz kablo, yerli üretim · CE · IP65. Ticari ve iş yeri uygulamaları için. Üreticisinden teklif alın.","focusKeyword":"type 2 şarj kablosu 16a trifaze 15m","keywords":"type 2 şarj kablosu 16a trifaze, ev şarj kablosu trifaze, 15m şarj kablosu, 11 kw mod 3 şarj seti, elektrikli araç şarj kablosu, yerli ev şarj kablosu, bemis type 2 kablo"},
  "sarj-seti-32a-trifaze-3m": {"metaTitle":"Type 2 Şarj Kablosu 32A Trifaze 3m – 22 kW","metaDescription":"Type 2 EV şarj kablosu 32A trifaze 3m, 22 kW maksimum AC Mod 3 şarj seti; halojensiz kablo, yerli üretim · CE · IP65. Hızlı AC kurulumlara uygun. Üreticisinden teklif alın.","focusKeyword":"type 2 şarj kablosu 32a trifaze","keywords":"type 2 şarj kablosu 32a trifaze, ev şarj kablosu trifaze, 22 kw mod 3 şarj seti, hızlı ac şarj kablosu, elektrikli araç şarj kablosu, yerli ev şarj kablosu, bemis type 2 kablo"},
  "sarj-seti-32a-trifaze-5m": {"metaTitle":"Type 2 Şarj Kablosu 32A Trifaze 5m – 22 kW","metaDescription":"Type 2 EV şarj kablosu 32A trifaze 5m, 22 kW maksimum AC Mod 3 şarj seti; halojensiz kablo, yerli üretim · CE · IP65. Hızlı AC kurulumlara uygun. Üreticisinden teklif alın.","focusKeyword":"type 2 şarj kablosu 32a trifaze 5m","keywords":"type 2 şarj kablosu 32a trifaze, ev şarj kablosu trifaze, 5m şarj kablosu, 22 kw mod 3 şarj seti, hızlı ac şarj kablosu, yerli ev şarj kablosu, bemis type 2 kablo"},
  "sarj-seti-32a-trifaze-7m": {"metaTitle":"Type 2 Şarj Kablosu 32A Trifaze 7m – 22 kW","metaDescription":"Type 2 EV şarj kablosu 32A trifaze 7m, 22 kW maksimum AC Mod 3 şarj seti; halojensiz kablo, yerli üretim · CE · IP65. Hızlı AC kurulumlara uygun. Üreticisinden teklif alın.","focusKeyword":"type 2 şarj kablosu 32a trifaze 7m","keywords":"type 2 şarj kablosu 32a trifaze, ev şarj kablosu trifaze, 7m şarj kablosu, 22 kw mod 3 şarj seti, hızlı ac şarj kablosu, yerli ev şarj kablosu, bemis type 2 kablo"},
  "sarj-seti-32a-trifaze-8m": {"metaTitle":"Type 2 Şarj Kablosu 32A Trifaze 8m – 22 kW","metaDescription":"Type 2 EV şarj kablosu 32A trifaze 8m, 22 kW maksimum AC Mod 3 şarj seti; halojensiz kablo, yerli üretim · CE · IP65. Hızlı AC kurulumlara uygun. Üreticisinden teklif alın.","focusKeyword":"type 2 şarj kablosu 32a trifaze 8m","keywords":"type 2 şarj kablosu 32a trifaze, ev şarj kablosu trifaze, 8m şarj kablosu, 22 kw mod 3 şarj seti, hızlı ac şarj kablosu, yerli ev şarj kablosu, bemis type 2 kablo"},
  "sarj-seti-32a-trifaze-10m": {"metaTitle":"Type 2 Şarj Kablosu 32A Trifaze 10m – 22 kW","metaDescription":"Type 2 EV şarj kablosu 32A trifaze 10m, 22 kW maksimum AC Mod 3 şarj seti; halojensiz kablo, yerli üretim · CE · IP65. Hızlı AC kurulumlara uygun. Üreticisinden teklif alın.","focusKeyword":"type 2 şarj kablosu 32a trifaze 10m","keywords":"type 2 şarj kablosu 32a trifaze, ev şarj kablosu trifaze, 10m şarj kablosu, 22 kw mod 3 şarj seti, hızlı ac şarj kablosu, yerli ev şarj kablosu, bemis type 2 kablo"},
  "sarj-seti-32a-trifaze-15m": {"metaTitle":"Type 2 Şarj Kablosu 32A Trifaze 15m – 22 kW","metaDescription":"Type 2 EV şarj kablosu 32A trifaze 15m, 22 kW maksimum AC Mod 3 şarj seti; halojensiz kablo, yerli üretim · CE · IP65. Hızlı AC kurulumlara uygun. Üreticisinden teklif alın.","focusKeyword":"type 2 şarj kablosu 32a trifaze 15m","keywords":"type 2 şarj kablosu 32a trifaze, ev şarj kablosu trifaze, 15m şarj kablosu, 22 kw mod 3 şarj seti, hızlı ac şarj kablosu, yerli ev şarj kablosu, bemis type 2 kablo"},
  "tek-cikisli-v2l-adaptor-hyundai": {"metaTitle":"Tek Çıkışlı V2L Adaptör — Hyundai · Kia","metaDescription":"V2L adaptör: Hyundai, Kia ve Ssangyong'un Type 2 soketini schuko prize çevirir, aracı seyyar güç kaynağı yapar. Yerli üretim · CE · IP65. Üreticisinden teklif alın.","focusKeyword":"v2l adaptör hyundai","keywords":"v2l adaptör, tek çıkışlı v2l, hyundai v2l adaptör, kia v2l, type 2 schuko adaptör, yerli, bemis"},
  "tek-cikisli-v2l-adaptor-mg": {"metaTitle":"Tek Çıkışlı V2L Adaptör — MG Uyumlu","metaDescription":"V2L adaptör: MG araçların Type 2 şarj soketini standart schuko prize çevirir; kamp ve acil senaryolar için. Yerli üretim · CE · IP65. Üreticisinden teklif alın.","focusKeyword":"mg v2l adaptör","keywords":"v2l adaptör, tek çıkışlı v2l, mg v2l adaptör, type 2 schuko adaptör, araçtan elektrik, yerli, bemis"},
  "tek-cikisli-v2l-adaptor-byd": {"metaTitle":"Tek Çıkışlı V2L Adaptör — BYD · Skywell","metaDescription":"V2L adaptör: BYD ve Skywell araçların Type 2 soketini schuko prize çevirir; kamp, atölye ve acil kullanım için. Yerli üretim · CE · IP65. Üreticisinden teklif alın.","focusKeyword":"byd v2l adaptör","keywords":"v2l adaptör, tek çıkışlı v2l, byd v2l adaptör, skywell v2l, type 2 schuko adaptör, yerli, bemis"},
  "tekli-priz-uzatma-v2l-adaptor-hyundai": {"metaTitle":"Tekli Priz Uzatma V2L Adaptör — 3m Hyundai","metaDescription":"V2L adaptör: 3 metre kabloyla tek schuko çıkış; Hyundai, Kia, Ssangyong aracı seyyar güç kaynağına çevirir. Yerli üretim · CE · IP65. Üreticisinden teklif alın.","focusKeyword":"tekli priz uzatma v2l adaptör hyundai","keywords":"v2l adaptör, priz uzatma v2l, hyundai v2l adaptör, kia v2l, 3 metre v2l kablo, araçtan elektrik, yerli, bemis"},
  "tekli-priz-uzatma-v2l-adaptor-mg": {"metaTitle":"Tekli Priz Uzatma V2L Adaptör — 3m MG","metaDescription":"V2L adaptör: 3 metre kabloyla tek schuko çıkış; MG aracınızı 3 metre mesafeden besleyen seyyar güç kaynağına çevirir. Yerli üretim · CE · IP65. Üreticisinden teklif alın.","focusKeyword":"tekli priz uzatma v2l adaptör mg","keywords":"v2l adaptör, priz uzatma v2l, mg v2l adaptör, 3 metre v2l kablo, schuko çıkış, araçtan elektrik, yerli, bemis"},
  "tekli-priz-uzatma-v2l-adaptor-byd": {"metaTitle":"Tekli Priz Uzatma V2L Adaptör — 3m BYD","metaDescription":"V2L adaptör: 3 metre kabloyla tek schuko çıkış; BYD ve Skywell aracı 3 metre mesafeden besleyen güç kaynağına çevirir. Yerli üretim · CE · IP65. Üreticisinden teklif alın.","focusKeyword":"tekli priz uzatma v2l adaptör byd","keywords":"v2l adaptör, priz uzatma v2l, byd v2l adaptör, skywell v2l, 3 metre v2l kablo, araçtan elektrik, yerli, bemis"},
  "2li-priz-uzatma-v2l-adaptor-hyundai": {"metaTitle":"2'li Priz Uzatma V2L Adaptör — Hyundai · Kia","metaDescription":"V2L adaptör: 3 metre kabloyla çift schuko çıkış; Hyundai, Kia, Ssangyong aracından aynı anda iki cihaz besler. Yerli üretim · CE · IP65. Üreticisinden teklif alın.","focusKeyword":"2'li priz uzatma v2l adaptör hyundai","keywords":"v2l adaptör, 2'li priz uzatma v2l, hyundai v2l adaptör, kia v2l, çift schuko çıkış, araçtan elektrik, yerli, bemis"},
  "2li-priz-uzatma-v2l-adaptor-mg": {"metaTitle":"2'li Priz Uzatma V2L Adaptör — 3m MG","metaDescription":"V2L adaptör: 3 metre kabloyla çift schuko çıkış; MG aracından aynı anda iki cihazı besler, saha ve atölye için. Yerli üretim · CE · IP65. Üreticisinden teklif alın.","focusKeyword":"2'li priz uzatma v2l adaptör mg","keywords":"v2l adaptör, 2'li priz uzatma v2l, mg v2l adaptör, çift schuko çıkış, 3 metre v2l kablo, araçtan elektrik, yerli, bemis"},
  "2li-priz-uzatma-v2l-adaptor-byd": {"metaTitle":"2'li Priz Uzatma V2L Adaptör — BYD · Skywell","metaDescription":"V2L adaptör: 3 metre kabloyla çift schuko çıkış; BYD ve Skywell aracından aynı anda iki cihaz besler. Yerli üretim · CE · IP65. Üreticisinden teklif alın.","focusKeyword":"2'li priz uzatma v2l adaptör byd","keywords":"v2l adaptör, 2'li priz uzatma v2l, byd v2l adaptör, skywell v2l, çift schuko çıkış, araçtan elektrik, yerli, bemis"},
  "3lu-priz-uzatma-v2l-adaptor-hyundai": {"metaTitle":"3'lü Priz Uzatma V2L Adaptör — Hyundai · Kia","metaDescription":"V2L adaptör: 3 metre kabloyla üç schuko çıkış; Hyundai, Kia, Ssangyong aracını kompakt jeneratöre çevirir. Yerli üretim · CE · IP65. Üreticisinden teklif alın.","focusKeyword":"3'lü priz uzatma v2l adaptör hyundai","keywords":"v2l adaptör, 3'lü priz uzatma v2l, hyundai v2l adaptör, kia v2l, üç schuko çıkış, araçtan elektrik, yerli, bemis"},
  "3lu-priz-uzatma-v2l-adaptor-mg": {"metaTitle":"3'lü Priz Uzatma V2L Adaptör — 3m MG","metaDescription":"V2L adaptör: 3 metre kabloyla üç schuko çıkış; MG aracını şantiye ve etkinlikte kompakt jeneratöre çevirir. Yerli üretim · CE · IP65. Üreticisinden teklif alın.","focusKeyword":"3'lü priz uzatma v2l adaptör mg","keywords":"v2l adaptör, 3'lü priz uzatma v2l, mg v2l adaptör, üç schuko çıkış, 3 metre v2l kablo, araçtan elektrik, yerli, bemis"},
  "3lu-priz-uzatma-v2l-adaptor-byd": {"metaTitle":"3'lü Priz Uzatma V2L Adaptör — BYD · Skywell","metaDescription":"V2L adaptör: 3 metre kabloyla üç schuko çıkış; BYD ve Skywell aracını kompakt jeneratöre çevirir, çoklu cihaz besler. Yerli üretim · CE · IP65. Üreticisinden teklif alın.","focusKeyword":"3'lü priz uzatma v2l adaptör byd","keywords":"v2l adaptör, 3'lü priz uzatma v2l, byd v2l adaptör, skywell v2l, üç schuko çıkış, araçtan elektrik, yerli, bemis"},
  "c2l-tekli-priz-uzatma-fisli-adaptor": {"metaTitle":"C2L Tekli Priz Uzatma Fişli Adaptör — 3m","metaDescription":"C2L adaptör: 3 metre kabloyla tek schuko çıkış; AC şarj cihazının çıkışını harici güç kaynağı yapar, saha ve atölye için. Yerli üretim · CE · IP65. Üreticisinden teklif alın.","focusKeyword":"c2l adaptör tekli priz","keywords":"c2l adaptör, tekli priz uzatma c2l, charger to load adaptör, ac şarj çıkışı, schuko adaptör, saha enerji, yerli, bemis"},
  "c2l-2li-priz-uzatma-fisli-adaptor": {"metaTitle":"C2L 2'li Priz Uzatma Fişli Adaptör — 3m","metaDescription":"C2L adaptör: 3 metre kabloyla çift schuko çıkış; şarj istasyonu çıkışını iki yüke dağıtır, geçici saha kurulumları için. Yerli üretim · CE · IP65. Üreticisinden teklif alın.","focusKeyword":"c2l adaptör 2'li priz","keywords":"c2l adaptör, 2'li priz uzatma c2l, charger to load adaptör, çift schuko çıkış, şarj istasyonu çıkışı, saha enerji, yerli, bemis"},
  "c2l-3lu-priz-uzatma-fisli-adaptor": {"metaTitle":"C2L 3'lü Priz Uzatma Fişli Adaptör — 3m","metaDescription":"C2L adaptör: 3 metre kabloyla üç schuko çıkış; şarj istasyonu çıkışını üç yüke dağıtarak çoklu ekipmanı besler. Yerli üretim · CE · IP65. Üreticisinden teklif alın.","focusKeyword":"c2l adaptör 3'lü priz","keywords":"c2l adaptör, 3'lü priz uzatma c2l, charger to load adaptör, üç schuko çıkış, şarj istasyonu çıkışı, çoklu ekipman, yerli, bemis"},
  "c2l-5-32a-prizli-uzatma-fisli-adaptor": {"metaTitle":"C2L 5/32A Prizli Uzatma Fişli Adaptör — 3m","metaDescription":"C2L adaptör: 3 metre kabloyla 5/32A endüstriyel CEE çıkış; şarj istasyonu çıkışını yüksek-akımlı sanayi ekipmanına aktarır. Yerli üretim · CE · IP65. Üreticisinden teklif alın.","focusKeyword":"c2l adaptör 5/32a priz","keywords":"c2l adaptör, 5/32a cee priz, charger to load adaptör, endüstriyel priz adaptör, şarj istasyonu çıkışı, şantiye enerji, yerli, bemis"},
  "c2c-charger-to-caravan-adaptor": {"metaTitle":"C2C Charger to Caravan Adaptör — 3/16A Type 2","metaDescription":"C2C adaptör: 3 metre kabloyla 3/16A CEE girişini Type 2 monofaze 16A fişe çevirir; karavanların şarj istasyonundan enerji almasını sağlar. Yerli üretim · CE · IP65. Üreticisinden","focusKeyword":"c2c karavan adaptör","keywords":"c2c adaptör, charger to caravan adaptör, karavan şarj adaptör, type 2 16a fiş, cee priz adaptör, mobil ünite enerji, yerli, bemis"},
  "cee-norm-adaptor-3-2-5-116a-fis-532a-priz": {"metaTitle":"CEE Norm Adaptör 16A Fiş 32A Priz Dönüştürücü","metaDescription":"EV şarj uzatma & dönüştürücü: 30 cm kablolu CEE Norm adaptör, 1/16A fiş → 5/32A priz, 3×2,5 mm² TTR. Yerli üretim · CE · IP65. Üreticisinden teklif alın.","focusKeyword":"cee norm adaptör 16a fiş 32a priz","keywords":"cee norm adaptör, fiş priz dönüştürücü, 16a 32a adaptör, ev şarj dönüştürücü, 3x2.5 ttr kablo, yerli, bemis"},
  "cee-norm-adaptor-3-2-5-116a-fis-332a-priz": {"metaTitle":"CEE Norm Adaptör 16A Fiş 3 Pin 32A Priz","metaDescription":"EV şarj uzatma & dönüştürücü: 30 cm kablolu CEE Norm adaptör, 1/16A fiş → 3/32A priz, 3×2,5 mm² TTR. Yerli üretim · CE · IP65. Üreticisinden teklif alın.","focusKeyword":"cee norm adaptör 16a 3 pin 32a","keywords":"cee norm adaptör, fiş priz dönüştürücü, 16a 32a adaptör, 3 pinli priz, ev şarj dönüştürücü, yerli, bemis"},
  "cee-norm-adaptor-3-2-5-332a-fis-116a-priz": {"metaTitle":"CEE Norm Adaptör 32A Fiş 16A Priz Dönüştürücü","metaDescription":"EV şarj uzatma & dönüştürücü: 30 cm kablolu CEE Norm adaptör, 3/32A fiş → 1/16A priz, 3×2,5 mm² TTR. Yerli üretim · CE · IP65. Üreticisinden teklif alın.","focusKeyword":"cee norm adaptör 32a fiş 16a priz","keywords":"cee norm adaptör, fiş priz dönüştürücü, 32a 16a adaptör, ev şarj dönüştürücü, 3x2.5 ttr kablo, yerli, bemis"},
  "cee-norm-adaptor-3-6-332a-fis-532a-priz": {"metaTitle":"CEE Norm Adaptör 3×6 32A Yüksek Akım Dönüştürücü","metaDescription":"EV şarj uzatma & dönüştürücü: 30 cm kablolu yüksek akım CEE Norm adaptör, 3/32A fiş → 5/32A priz, 3×6 mm² TTR. Yerli üretim · CE · IP65. Üreticisinden teklif alın.","focusKeyword":"cee norm adaptör 3x6 32a yüksek akım","keywords":"cee norm adaptör, fiş priz dönüştürücü, 32a yüksek akım adaptör, 3x6 ttr kablo, ev şarj dönüştürücü, yerli, bemis"},
  "standart-adaptor-3-2-5-116a-fis-316a-priz": {"metaTitle":"Standart Adaptör 16A Fiş 16A Priz Dönüştürücü","metaDescription":"EV şarj uzatma & dönüştürücü: kompakt fiş-priz adaptör, 1/16A fiş → 3/16A priz, 3×2,5 mm² TTR ekonomik çözüm. Yerli üretim · CE · IP65. Üreticisinden teklif alın.","focusKeyword":"standart adaptör 16a fiş priz dönüştürücü","keywords":"standart adaptör, fiş priz dönüştürücü, 16a adaptör, ev şarj dönüştürücü, 3x2.5 ttr kablo, yerli, bemis"},
  "standart-adaptor-3-2-5-316a-fis-116a-priz": {"metaTitle":"Standart Adaptör 16A Priz Fiş Dönüştürücü","metaDescription":"EV şarj uzatma & dönüştürücü: kompakt fiş-priz adaptör, 3/16A fiş → 1/16A priz, 3×2,5 mm² TTR ekonomik çözüm. Yerli üretim · CE · IP65. Üreticisinden teklif alın.","focusKeyword":"standart adaptör 16a priz fiş dönüştürücü","keywords":"standart adaptör, fiş priz dönüştürücü, 16a adaptör, ev şarj dönüştürücü, 3x2.5 ttr kablo, yerli, bemis"},
  "seyyar-uzatma-kablosu-monofaze-3-2-5-5m-standart": {"metaTitle":"Seyyar Uzatma Kablosu Monofaze 3×2,5 5m 16A","metaDescription":"EV şarj uzatma & dönüştürücü kablo: monofaze 16A, 3×2,5 mm² TTR halojensiz seyyar uzatma kablosu 5m. Yerli üretim · CE · IP65. Üreticisinden teklif alın.","focusKeyword":"seyyar uzatma kablosu monofaze 16a 5m","keywords":"seyyar uzatma kablosu, monofaze uzatma kablosu, 16a uzatma kablosu, ev şarj uzatma, 3x2.5 ttr kablo, yerli, bemis"},
  "seyyar-uzatma-kablosu-monofaze-3-2-5-10m-standart": {"metaTitle":"Seyyar Uzatma Kablosu Monofaze 3×2,5 10m 16A","metaDescription":"EV şarj uzatma & dönüştürücü kablo: monofaze 16A, 3×2,5 mm² TTR halojensiz seyyar uzatma kablosu 10m. Yerli üretim · CE · IP65. Üreticisinden teklif alın.","focusKeyword":"seyyar uzatma kablosu monofaze 16a 10m","keywords":"seyyar uzatma kablosu, monofaze uzatma kablosu, 16a uzatma kablosu, ev şarj uzatma, 3x2.5 ttr kablo, yerli, bemis"},
  "seyyar-uzatma-kablosu-monofaze-3-2-5-10m-ip68": {"metaTitle":"Seyyar Uzatma Kablosu Monofaze IP68 10m 16A","metaDescription":"EV şarj uzatma & dönüştürücü kablo: monofaze 16A IP68, 3×2,5 mm² TTR halojensiz seyyar uzatma kablosu 10m. Yerli üretim · CE · IP65. Üreticisinden teklif alın.","focusKeyword":"seyyar uzatma kablosu ip68 16a 10m","keywords":"seyyar uzatma kablosu, ip68 uzatma kablosu, monofaze uzatma kablosu, 16a uzatma kablosu, ev şarj uzatma, yerli, bemis"},
  "seyyar-uzatma-kablosu-ceenorm-3-2-5-116a-332a-5m": {"metaTitle":"CEE Norm Uzatma Kablosu 16A 3 Pin 32A 5m","metaDescription":"EV şarj uzatma & dönüştürücü kablo: CEE Norm 1/16A → 3/32A dönüşümlü seyyar uzatma 5m, 3×2,5 mm² TTR. Yerli üretim · CE · IP65. Üreticisinden teklif alın.","focusKeyword":"cee norm uzatma kablosu 16a 32a 5m","keywords":"cee norm uzatma kablosu, dönüştürücü uzatma kablosu, 16a 32a uzatma, ev şarj uzatma, 3x2.5 ttr kablo, yerli, bemis"},
  "seyyar-uzatma-kablosu-ceenorm-3-2-5-116a-332a-10m": {"metaTitle":"CEE Norm Uzatma Kablosu 16A 3 Pin 32A 10m","metaDescription":"EV şarj uzatma & dönüştürücü kablo: CEE Norm 1/16A → 3/32A dönüşümlü seyyar uzatma 10m, 3×2,5 mm² TTR. Yerli üretim · CE · IP65. Üreticisinden teklif alın.","focusKeyword":"cee norm uzatma kablosu 16a 32a 10m","keywords":"cee norm uzatma kablosu, dönüştürücü uzatma kablosu, 16a 32a uzatma, ev şarj uzatma, 3x2.5 ttr kablo, yerli, bemis"},
  "seyyar-uzatma-kablosu-ceenorm-3-2-5-116a-532a-5m": {"metaTitle":"CEE Norm Uzatma Kablosu 16A 5 Pin 32A 5m","metaDescription":"EV şarj uzatma & dönüştürücü kablo: CEE Norm 1/16A → 5/32A dönüşümlü seyyar uzatma 5m, 3×2,5 mm² TTR. Yerli üretim · CE · IP65. Üreticisinden teklif alın.","focusKeyword":"cee norm uzatma kablosu 16a 5 pin 32a 5m","keywords":"cee norm uzatma kablosu, dönüştürücü uzatma kablosu, 16a 32a uzatma, 5 pinli uzatma, ev şarj uzatma, yerli, bemis"},
  "seyyar-uzatma-kablosu-ceenorm-3-2-5-116a-532a-10m": {"metaTitle":"CEE Norm Uzatma Kablosu 16A 5 Pin 32A 10m","metaDescription":"EV şarj uzatma & dönüştürücü kablo: CEE Norm 1/16A → 5/32A dönüşümlü seyyar uzatma 10m, 3×2,5 mm² TTR. Yerli üretim · CE · IP65. Üreticisinden teklif alın.","focusKeyword":"cee norm uzatma kablosu 16a 5 pin 32a 10m","keywords":"cee norm uzatma kablosu, dönüştürücü uzatma kablosu, 16a 32a uzatma, 5 pinli uzatma, ev şarj uzatma, yerli, bemis"},
  "seyyar-uzatma-kablosu-ceenorm-3-6-332a-5m": {"metaTitle":"CEE Norm Trifaze Uzatma Kablosu 3×6 32A 5m","metaDescription":"EV şarj uzatma & dönüştürücü kablo: trifaze 32A, 3×6 mm² TTR yüksek akım seyyar uzatma 5m, şantiye için. Yerli üretim · CE · IP65. Üreticisinden teklif alın.","focusKeyword":"cee norm trifaze uzatma kablosu 32a 5m","keywords":"cee norm uzatma kablosu, trifaze uzatma kablosu, 32a uzatma kablosu, 3x6 ttr kablo, ev şarj uzatma, yerli, bemis"},
  "seyyar-uzatma-kablosu-ceenorm-3-6-332a-10m": {"metaTitle":"CEE Norm Trifaze Uzatma Kablosu 3×6 32A 10m","metaDescription":"EV şarj uzatma & dönüştürücü kablo: trifaze 32A, 3×6 mm² TTR yüksek akım seyyar uzatma 10m, şantiye için. Yerli üretim · CE · IP65. Üreticisinden teklif alın.","focusKeyword":"cee norm trifaze uzatma kablosu 32a 10m","keywords":"cee norm uzatma kablosu, trifaze uzatma kablosu, 32a uzatma kablosu, 3x6 ttr kablo, ev şarj uzatma, yerli, bemis"},
  "seyyar-uzatma-kablosu-ceenorm-5-6-532a-5m": {"metaTitle":"CEE Norm Trifaze Uzatma Kablosu 5×6 32A 5m","metaDescription":"EV şarj uzatma & dönüştürücü kablo: trifaze + nötr + toprak 32A, 5×6 mm² TTR seyyar uzatma 5m. Yerli üretim · CE · IP65. Üreticisinden teklif alın.","focusKeyword":"cee norm 5x6 trifaze uzatma kablosu 32a 5m","keywords":"cee norm uzatma kablosu, trifaze uzatma kablosu, 32a uzatma kablosu, 5x6 ttr kablo, 5 telli uzatma, yerli, bemis"},
  "seyyar-uzatma-kablosu-ceenorm-5-6-532a-10m": {"metaTitle":"CEE Norm Trifaze Uzatma Kablosu 5×6 32A 10m","metaDescription":"EV şarj uzatma & dönüştürücü kablo: trifaze + nötr + toprak 32A, 5×6 mm² TTR seyyar uzatma 10m. Yerli üretim · CE · IP65. Üreticisinden teklif alın.","focusKeyword":"cee norm 5x6 trifaze uzatma kablosu 32a 10m","keywords":"cee norm uzatma kablosu, trifaze uzatma kablosu, 32a uzatma kablosu, 5x6 ttr kablo, 5 telli uzatma, yerli, bemis"},
  "sarj-kablosu-cantasi-premium": {"metaTitle":"Şarj Kablosu Çantası Premium — Type 2","metaDescription":"EV şarj aksesuarı: Type 2 kabloları için premium fermuarlı taşıma çantası, su iticili dış kumaş ve koruyucu iç hücre. Yerli üretim · CE · IP65. Üreticisinden teklif alın.","focusKeyword":"type 2 şarj kablosu çantası","keywords":"şarj kablosu çantası, type 2 kablo çantası, ev şarj aksesuarı, taşıma çantası, premium, yerli, bemis"},
  "sarj-kablosu-cantasi-standart": {"metaTitle":"Şarj Kablosu Çantası Standart — Type 2","metaDescription":"EV şarj aksesuarı: Type 2 kabloları için standart fermuarlı taşıma çantası, su iticili kumaş ve kablo ucunu koruyan iç hücre. Yerli üretim · CE · IP65. Üreticisinden teklif alın.","focusKeyword":"type 2 şarj kablosu çantası","keywords":"şarj kablosu çantası, type 2 kablo çantası, ev şarj aksesuarı, taşıma çantası, standart, yerli, bemis"},
  "mobile-charger-cantasi-kucuk-mini-mono": {"metaTitle":"Mobile Charger Çantası Küçük — Mini-Mono","metaDescription":"EV şarj aksesuarı: taşınabilir Bemis şarj cihazları için küçük Mini-Mono taşıma çantası, cihaz ve kablo için ayrı bölmeler. Yerli üretim · CE · IP65. Üreticisinden teklif alın.","focusKeyword":"mobile charger taşıma çantası","keywords":"mobile charger çantası, taşınabilir şarj çantası, ev şarj aksesuarı, mini-mono, taşıma çantası, yerli, bemis"},
  "mobile-charger-cantasi-buyuk-pro": {"metaTitle":"Mobile Charger Çantası Büyük — Pro","metaDescription":"EV şarj aksesuarı: taşınabilir Bemis şarj cihazları için büyük Pro taşıma çantası, cihaz, kablo ve adaptör için ayrı bölmeler. Yerli üretim · CE · IP65. Üreticisinden teklif alın.","focusKeyword":"mobile charger taşıma çantası","keywords":"mobile charger çantası, taşınabilir şarj çantası, ev şarj aksesuarı, pro çanta, taşıma çantası, yerli, bemis"},
  "priz-tutucu-genel-priz-tutucu": {"metaTitle":"Priz Tutucu — Type 2 Duvar/Pano Montaj","metaDescription":"EV şarj aksesuarı: kullanılmayan Type 2 prizi asarak saklayan duvar veya pano montajlı tutucu. Kabloyu yerden uzak tutar. Yerli üretim · CE · IP65. Üreticisinden teklif alın.","focusKeyword":"type 2 priz tutucu","keywords":"priz tutucu, type 2 priz tutucu, ev şarj aksesuarı, duvar tutucu, pano montaj, yerli, bemis"},
  "charger-priz-tutucu-charger-serisi": {"metaTitle":"Charger Priz Tutucu — AC Wallbox Serisi","metaDescription":"EV şarj aksesuarı: Bemis Charger serisi AC wallbox cihazları için özel priz tutucu, gövde rengiyle uyumlu hızlı kelepçe. Yerli üretim · CE · IP65. Üreticisinden teklif alın.","focusKeyword":"charger serisi priz tutucu","keywords":"charger priz tutucu, ac wallbox priz tutucu, ev şarj aksesuarı, charger serisi, priz tutucu, yerli, bemis"},
  "pedestal-standart-yukseklik": {"metaTitle":"Pedestal — AC Şarj İstasyonu Kaide","metaDescription":"EV şarj aksesuarı: AC şarj istasyonu için zemine montajlı paslanmaz çelik pedestal kaide, tek/çift cihaz montajı, iç kablo kanalları. Yerli üretim · CE · IP65. Üreticisinden","focusKeyword":"ev şarj istasyonu pedestal","keywords":"pedestal, şarj istasyonu kaide, ev şarj aksesuarı, ac şarj direği, paslanmaz çelik kaide, yerli, bemis"},
  "mobile-charger-duvar-aski-aparati-mini-mono": {"metaTitle":"Mobile Charger Duvar Askı — Mini-Mono","metaDescription":"EV şarj aksesuarı: taşınabilir Bemis şarj cihazları için Mini-Mono duvara montaj askı aparatı, cihazı garaj ve atölyede hazır tutar. Yerli üretim · CE · IP65. Üreticisinden teklif","focusKeyword":"mobile charger duvar askı aparatı","keywords":"mobile charger duvar askı, duvar askı aparatı, ev şarj aksesuarı, mini-mono, taşınabilir şarj askısı, yerli, bemis"},
  "mobile-charger-duvar-aski-aparati-pro": {"metaTitle":"Mobile Charger Duvar Askı — Pro","metaDescription":"EV şarj aksesuarı: taşınabilir Bemis şarj cihazları için Pro duvara montaj askı aparatı, cihazı garaj, atölye ve tesiste düzenli tutar. Yerli üretim · CE · IP65. Üreticisinden","focusKeyword":"mobile charger duvar askı aparatı","keywords":"mobile charger duvar askı, duvar askı aparatı, ev şarj aksesuarı, pro askı, taşınabilir şarj askısı, yerli, bemis"},
  "v2l-ve-c2l-adaptor-cantasi-standart": {"metaTitle":"V2L ve C2L Adaptör Çantası — Standart","metaDescription":"EV şarj aksesuarı: V2L ve C2L adaptörleri için kompakt taşıma çantası, adaptör ve uzatma kablosu için tek bölmeli düzenleme. Yerli üretim · CE · IP65. Üreticisinden teklif alın.","focusKeyword":"v2l c2l adaptör çantası","keywords":"v2l adaptör çantası, c2l adaptör çantası, ev şarj aksesuarı, adaptör taşıma çantası, taşıma çantası, yerli, bemis"},
  "bevdc-40-1": {"metaTitle":"DC Hızlı Şarj Ünitesi BEVDC 40 — 40kW CCS2","metaDescription":"DC hızlı şarj ünitesi BEVDC 40, tek CCS2 çıkışlı 40 kW kompakt istasyon; kafe, otel ve otopark için ideal · yerli üretim · CE · IP65. Üreticisinden teklif alın.","focusKeyword":"dc hızlı şarj ünitesi 40kw","keywords":"dc hızlı şarj ünitesi, bevdc 40, 40kw dc şarj istasyonu, ccs2 hızlı şarj, ocpp dc şarj, yerli dc şarj cihazı, bemis dc şarj, otopark şarj istasyonu"},
  "bevdc-80-2": {"metaTitle":"DC Hızlı Şarj Ünitesi BEVDC 80 — Çift CCS2 80kW","metaDescription":"DC hızlı şarj ünitesi BEVDC 80, çift CCS2 çıkışlı 80 kW istasyon; iki aracı eş zamanlı şarj eder, AVM ve kampüs için · yerli üretim · CE · IP65. Üreticisinden teklif alın.","focusKeyword":"dc hızlı şarj ünitesi 80kw","keywords":"dc hızlı şarj ünitesi, bevdc 80, 80kw dc şarj istasyonu, çift ccs2 şarj, ocpp dc şarj, yerli dc şarj cihazı, bemis dc şarj, avm şarj istasyonu"},
  "bevdc-120-1": {"metaTitle":"DC Hızlı Şarj Ünitesi BEVDC 120 — 120kW CCS2","metaDescription":"DC hızlı şarj ünitesi BEVDC 120, 120 kW CCS2 istasyon; otoyol dinlenme alanı ve filo merkezleri için yüksek güç · yerli üretim · CE · IP65. Üreticisinden teklif alın.","focusKeyword":"dc hızlı şarj ünitesi 120kw","keywords":"dc hızlı şarj ünitesi, bevdc 120, 120kw dc şarj istasyonu, ccs2 hızlı şarj, ocpp dc şarj, yerli dc şarj cihazı, bemis dc şarj, otoyol şarj istasyonu"},
  "bevdc-120-2": {"metaTitle":"Çift Soketli DC Şarj BEVDC 120 — 120kW CCS2","metaDescription":"DC hızlı şarj ünitesi BEVDC 120 çift soketli, 120 kW CCS2 istasyon; otoyol ve filo merkezleri için iki çıkış · yerli üretim · CE · IP65. Üreticisinden teklif alın.","focusKeyword":"çift soketli dc hızlı şarj ünitesi 120kw","keywords":"dc hızlı şarj ünitesi, bevdc 120 çift soket, 120kw dc şarj istasyonu, çift ccs2 şarj, ocpp dc şarj, yerli dc şarj cihazı, bemis dc şarj, filo şarj istasyonu"},
  "bevdc-160-2": {"metaTitle":"DC Hızlı Şarj Ünitesi BEVDC 160 — Çift CCS2","metaDescription":"DC hızlı şarj ünitesi BEVDC 160, çift CCS2 çıkışlı 160 kW yüksek güç istasyon; dinamik güç paylaşımıyla iki araç · yerli üretim · CE · IP65. Üreticisinden teklif alın.","focusKeyword":"dc hızlı şarj ünitesi 160kw","keywords":"dc hızlı şarj ünitesi, bevdc 160, 160kw dc şarj istasyonu, çift ccs2 şarj, yüksek güç dc şarj, yerli dc şarj cihazı, bemis dc şarj, ticari filo şarjı"},
  "bevdc-200-2": {"metaTitle":"DC Hızlı Şarj Ünitesi BEVDC 200 — Çift CCS2","metaDescription":"DC hızlı şarj ünitesi BEVDC 200, çift CCS2 çıkışlı 200 kW amiral istasyon; otoyol koridoru ve ultra hızlı şarj için · yerli üretim · CE · IP65. Üreticisinden teklif alın.","focusKeyword":"dc hızlı şarj ünitesi 200kw","keywords":"dc hızlı şarj ünitesi, bevdc 200, 200kw dc şarj istasyonu, çift ccs2 şarj, ultra hızlı dc şarj, yerli dc şarj cihazı, bemis dc şarj, otoyol şarj istasyonu"},
  "bir-ucu-acik-kablolu-sarj-prizi-5m-monofaze-3-7-kw-3x2-5-mm": {"metaTitle":"Bir Uçu Açık Kablolu Şarj Prizi 5m 3,7 kW","metaDescription":"Şarj ünitesi ekipmanı: bir ucu açık kablolu Type 2 şarj prizi, 5m monofaze 3,7 kW. OEM üretim hattına doğrudan terminasyon · yerli üretim · CE · IP65. Üreticisinden teklif alın.","focusKeyword":"bir ucu açık kablolu şarj prizi","keywords":"bir ucu açık kablolu şarj prizi, type 2 şarj prizi, monofaze şarj prizi 3,7 kw, şarj ünitesi ekipmanı, oem şarj prizi, yerli, bemis"},
  "bir-ucu-acik-kablolu-sarj-prizi-8m-monofaze-3-7-kw-3x2-5-mm": {"metaTitle":"Bir Uçu Açık Kablolu Şarj Prizi 8m 3,7 kW","metaDescription":"Şarj ünitesi ekipmanı: bir ucu açık kablolu Type 2 şarj prizi, 8m monofaze 3,7 kW. OEM üretim hattına doğrudan terminasyon · yerli üretim · CE · IP65. Üreticisinden teklif alın.","focusKeyword":"bir ucu açık kablolu şarj prizi","keywords":"bir ucu açık kablolu şarj prizi, type 2 şarj prizi, monofaze şarj prizi 3,7 kw, 8m şarj kablosu, şarj ünitesi ekipmanı, yerli, bemis"},
  "bir-ucu-acik-kablolu-sarj-prizi-5m-monofaze-7-4-kw-3x6-mm": {"metaTitle":"Bir Uçu Açık Kablolu Şarj Prizi 5m 7,4 kW","metaDescription":"Şarj ünitesi ekipmanı: bir ucu açık kablolu Type 2 şarj prizi, 5m monofaze 7,4 kW. OEM üretim hattına doğrudan terminasyon · yerli üretim · CE · IP65. Üreticisinden teklif alın.","focusKeyword":"bir ucu açık kablolu şarj prizi","keywords":"bir ucu açık kablolu şarj prizi, type 2 şarj prizi, monofaze şarj prizi 7,4 kw, şarj ünitesi ekipmanı, oem şarj prizi, yerli, bemis"},
  "bir-ucu-acik-kablolu-sarj-prizi-8m-monofaze-7-4-kw-3x6-mm": {"metaTitle":"Bir Uçu Açık Kablolu Şarj Prizi 8m 7,4 kW","metaDescription":"Şarj ünitesi ekipmanı: bir ucu açık kablolu Type 2 şarj prizi, 8m monofaze 7,4 kW. OEM üretim hattına doğrudan terminasyon · yerli üretim · CE · IP65. Üreticisinden teklif alın.","focusKeyword":"bir ucu açık kablolu şarj prizi","keywords":"bir ucu açık kablolu şarj prizi, type 2 şarj prizi, monofaze şarj prizi 7,4 kw, 8m şarj kablosu, şarj ünitesi ekipmanı, yerli, bemis"},
  "bir-ucu-acik-kablolu-sarj-prizi-5m-trifaze-11-kw-5x2-5-mm": {"metaTitle":"Bir Uçu Açık Kablolu Şarj Prizi 5m 11 kW","metaDescription":"Şarj ünitesi ekipmanı: bir ucu açık kablolu Type 2 şarj prizi, 5m trifaze 11 kW. OEM üretim hattına doğrudan terminasyon · yerli üretim · CE · IP65. Üreticisinden teklif alın.","focusKeyword":"bir ucu açık kablolu şarj prizi","keywords":"bir ucu açık kablolu şarj prizi, type 2 şarj prizi, trifaze şarj prizi 11 kw, şarj ünitesi ekipmanı, oem şarj prizi, yerli, bemis"},
  "bir-ucu-acik-kablolu-sarj-prizi-8m-trifaze-11-kw-5x2-5-mm": {"metaTitle":"Bir Uçu Açık Kablolu Şarj Prizi 8m 11 kW","metaDescription":"Şarj ünitesi ekipmanı: bir ucu açık kablolu Type 2 şarj prizi, 8m trifaze 11 kW. OEM üretim hattına doğrudan terminasyon · yerli üretim · CE · IP65. Üreticisinden teklif alın.","focusKeyword":"bir ucu açık kablolu şarj prizi","keywords":"bir ucu açık kablolu şarj prizi, type 2 şarj prizi, trifaze şarj prizi 11 kw, 8m şarj kablosu, şarj ünitesi ekipmanı, yerli, bemis"},
  "bir-ucu-acik-kablolu-sarj-prizi-5m-trifaze-22-kw-5x6-mm": {"metaTitle":"Bir Uçu Açık Kablolu Şarj Prizi 5m 22 kW","metaDescription":"Şarj ünitesi ekipmanı: bir ucu açık kablolu Type 2 şarj prizi, 5m trifaze 22 kW. OEM üretim hattına doğrudan terminasyon · yerli üretim · CE · IP65. Üreticisinden teklif alın.","focusKeyword":"bir ucu açık kablolu şarj prizi","keywords":"bir ucu açık kablolu şarj prizi, type 2 şarj prizi, trifaze şarj prizi 22 kw, şarj ünitesi ekipmanı, oem şarj prizi, yerli, bemis"},
  "bir-ucu-acik-kablolu-sarj-prizi-8m-trifaze-22-kw-5x6-mm": {"metaTitle":"Bir Uçu Açık Kablolu Şarj Prizi 8m 22 kW","metaDescription":"Şarj ünitesi ekipmanı: bir ucu açık kablolu Type 2 şarj prizi, 8m trifaze 22 kW. OEM üretim hattına doğrudan terminasyon · yerli üretim · CE · IP65. Üreticisinden teklif alın.","focusKeyword":"bir ucu açık kablolu şarj prizi","keywords":"bir ucu açık kablolu şarj prizi, type 2 şarj prizi, trifaze şarj prizi 22 kw, 8m şarj kablosu, şarj ünitesi ekipmanı, yerli, bemis"},
  "pano-prizi-monofaze-3-7-7-4-kw-3-noktadan-montaj": {"metaTitle":"Pano Prizi Monofaze 3,7-7,4 kW · 3 Nokta","metaDescription":"Şarj ünitesi ekipmanı: kilit motorlu Type 2 pano prizi, monofaze 3,7-7,4 kW, 3 noktadan montaj. AC şarj üreticilerine standart bileşen · yerli üretim · CE · IP65. Üreticisinden","focusKeyword":"type 2 pano prizi","keywords":"type 2 pano prizi, pano prizi monofaze, kilit motorlu pano prizi, şarj panosu prizi, şarj ünitesi ekipmanı, yerli, bemis"},
  "pano-prizi-monofaze-3-7-7-4-kw-4-noktadan-montaj": {"metaTitle":"Pano Prizi Monofaze 3,7-7,4 kW · 4 Nokta","metaDescription":"Şarj ünitesi ekipmanı: kilit motorlu Type 2 pano prizi, monofaze 3,7-7,4 kW, 4 noktadan montaj. AC şarj üreticilerine standart bileşen · yerli üretim · CE · IP65. Üreticisinden","focusKeyword":"type 2 pano prizi","keywords":"type 2 pano prizi, pano prizi monofaze, kilit motorlu pano prizi, 4 noktadan montaj pano prizi, şarj ünitesi ekipmanı, yerli, bemis"},
  "pano-prizi-trifaze-11-22-kw-3-noktadan-montaj": {"metaTitle":"Pano Prizi Trifaze 11-22 kW · 3 Nokta","metaDescription":"Şarj ünitesi ekipmanı: kilit motorlu Type 2 pano prizi, trifaze 11-22 kW, 3 noktadan montaj. AC şarj üreticilerine standart bileşen · yerli üretim · CE · IP65. Üreticisinden","focusKeyword":"type 2 pano prizi","keywords":"type 2 pano prizi, pano prizi trifaze, kilit motorlu pano prizi 22 kw, şarj panosu prizi, şarj ünitesi ekipmanı, yerli, bemis"},
  "pano-prizi-trifaze-11-22-kw-4-noktadan-montaj": {"metaTitle":"Pano Prizi Trifaze 11-22 kW · 4 Nokta","metaDescription":"Şarj ünitesi ekipmanı: kilit motorlu Type 2 pano prizi, trifaze 11-22 kW, 4 noktadan montaj. AC şarj üreticilerine standart bileşen · yerli üretim · CE · IP65. Üreticisinden","focusKeyword":"type 2 pano prizi","keywords":"type 2 pano prizi, pano prizi trifaze, kilit motorlu pano prizi 22 kw, 4 noktadan montaj pano prizi, şarj ünitesi ekipmanı, yerli, bemis"},
  "pano-prizi-kilit-motorsuz-monofaze-3-7-7-4-kw-3-noktadan-montaj": {"metaTitle":"Pano Prizi Kilit Motorsuz Monofaze · 3 Nokta","metaDescription":"Şarj ünitesi ekipmanı: kilit motorsuz ekonomik Type 2 pano prizi, monofaze 3,7-7,4 kW, 3 noktadan montaj · yerli üretim · CE · IP65. Üretici kurulumlarına uygun. Üreticisinden","focusKeyword":"kilit motorsuz pano prizi","keywords":"kilit motorsuz pano prizi, type 2 pano prizi, ekonomik pano prizi monofaze, şarj panosu prizi, şarj ünitesi ekipmanı, yerli, bemis"},
  "pano-prizi-kilit-motorsuz-monofaze-3-7-7-4-kw-4-noktadan-montaj": {"metaTitle":"Pano Prizi Kilit Motorsuz Monofaze · 4 Nokta","metaDescription":"Şarj ünitesi ekipmanı: kilit motorsuz ekonomik Type 2 pano prizi, monofaze 3,7-7,4 kW, 4 noktadan montaj · yerli üretim · CE · IP65. Üretici kurulumlarına uygun. Üreticisinden","focusKeyword":"kilit motorsuz pano prizi","keywords":"kilit motorsuz pano prizi, type 2 pano prizi, ekonomik pano prizi monofaze, 4 noktadan montaj pano prizi, şarj ünitesi ekipmanı, yerli, bemis"},
  "pano-prizi-kilit-motorsuz-trifaze-11-22-kw-3-noktadan-montaj": {"metaTitle":"Pano Prizi Kilit Motorsuz Trifaze · 3 Nokta","metaDescription":"Şarj ünitesi ekipmanı: kilit motorsuz ekonomik Type 2 pano prizi, trifaze 11-22 kW, 3 noktadan montaj · yerli üretim · CE · IP65. Üretici kurulumlarına uygun. Üreticisinden teklif","focusKeyword":"kilit motorsuz pano prizi","keywords":"kilit motorsuz pano prizi, type 2 pano prizi, ekonomik pano prizi trifaze, şarj panosu prizi 22 kw, şarj ünitesi ekipmanı, yerli, bemis"},
  "pano-prizi-kilit-motorsuz-trifaze-11-22-kw-4-noktadan-montaj": {"metaTitle":"Pano Prizi Kilit Motorsuz Trifaze · 4 Nokta","metaDescription":"Şarj ünitesi ekipmanı: kilit motorsuz ekonomik Type 2 pano prizi, trifaze 11-22 kW, 4 noktadan montaj · yerli üretim · CE · IP65. Üretici kurulumlarına uygun. Üreticisinden teklif","focusKeyword":"kilit motorsuz pano prizi","keywords":"kilit motorsuz pano prizi, type 2 pano prizi, ekonomik pano prizi trifaze, 4 noktadan montaj pano prizi, şarj ünitesi ekipmanı, yerli, bemis"},
  "bir-ucu-acik-enerji-kablosu-532a-trifaze-11-22-kw-5x6-mm": {"metaTitle":"Bir Ucu Açık Enerji Kablosu 5/32A Trifaze","metaDescription":"Şarj ünitesi ekipmanı: 1,5 m bir ucu açık enerji kablosu, 5/32A trifaze 11-22 kW. Cihaz iç bağlantısına doğrudan terminasyon · yerli üretim · CE · IP65. Üreticisinden teklif alın.","focusKeyword":"bir ucu açık enerji kablosu","keywords":"bir ucu açık enerji kablosu, enerji kablosu trifaze 5x6, 5/32a enerji kablosu, şarj cihazı kablosu, şarj ünitesi ekipmanı, yerli, bemis"},
  "bir-ucu-acik-enerji-kablosu-332a-monofaze-3-7-7-4-kw-3x6-mm": {"metaTitle":"Bir Ucu Açık Enerji Kablosu 3/32A Monofaze","metaDescription":"Şarj ünitesi ekipmanı: 1,5 m bir ucu açık enerji kablosu, 3/32A monofaze 3,7-7,4 kW. Cihaz iç bağlantısına doğrudan terminasyon · yerli üretim · CE · IP65. Üreticisinden teklif","focusKeyword":"bir ucu açık enerji kablosu","keywords":"bir ucu açık enerji kablosu, enerji kablosu monofaze 3x6, 3/32a enerji kablosu, şarj cihazı kablosu, şarj ünitesi ekipmanı, yerli, bemis"},
  "otomatli-ip44-kombinasyon-bd1m2123-1020-x": {"metaTitle":"Otomatlı IP44 Kombinasyon 3/32A · 1/16A","metaDescription":"Şarj ünitesi ekipmanı: IP44 otomatlı kombinasyon ünitesi, 3/32A · 1/16A yan. Mobil şarj cihazlarına entegre koruma + dağıtım · yerli üretim · CE. İç mekana uygun. Üreticisinden","focusKeyword":"otomatlı ip44 kombinasyon","keywords":"otomatlı ip44 kombinasyon, ip44 kombinasyon ünitesi, mobil şarj kombinasyon, şarj koruma dağıtım, şarj ünitesi ekipmanı, yerli, bemis"},
  "otomatli-ip44-kombinasyon-bd2m2134-1020-x": {"metaTitle":"Otomatlı IP44 Kombinasyon 5/32A · 1/16A","metaDescription":"Şarj ünitesi ekipmanı: IP44 otomatlı kombinasyon ünitesi, 5/32A · 1/16A ön. Mobil şarj cihazlarına entegre koruma + dağıtım · yerli üretim · CE. İç mekana uygun. Üreticisinden","focusKeyword":"otomatlı ip44 kombinasyon","keywords":"otomatlı ip44 kombinasyon, ip44 kombinasyon ünitesi 5/32a, mobil şarj kombinasyon, şarj koruma dağıtım, şarj ünitesi ekipmanı, yerli, bemis"},
  "otomatli-ip44-kombinasyon-bd2m2134-1231-x": {"metaTitle":"Otomatlı IP44 Kombinasyon 5/32A · 3/32A 220V","metaDescription":"Şarj ünitesi ekipmanı: IP44 otomatlı kombinasyon ünitesi, 5/32A · 3/32A 220V · 1/16A. Mobil şarj cihazlarına entegre koruma + dağıtım · yerli üretim · CE. Üreticisinden teklif","focusKeyword":"otomatlı ip44 kombinasyon","keywords":"otomatlı ip44 kombinasyon, ip44 kombinasyon ünitesi 220v, mobil şarj kombinasyon, şarj koruma dağıtım, şarj ünitesi ekipmanı, yerli, bemis"},
  "otomatli-ip66-kombinasyon-bd1m6119-1020-x": {"metaTitle":"Otomatlı IP66 Kombinasyon 3/32A · 1/16A","metaDescription":"Şarj ünitesi ekipmanı: IP66 otomatlı kombinasyon ünitesi, 3/32A · 1/16A yan. Toz ve su jetine karşı tam koruma, dış mekana uygun · yerli üretim · CE · IP66. Üreticisinden teklif","focusKeyword":"otomatlı ip66 kombinasyon","keywords":"otomatlı ip66 kombinasyon, ip66 kombinasyon ünitesi, dış mekan şarj kombinasyon, şarj koruma dağıtım, şarj ünitesi ekipmanı, yerli, bemis"},
  "otomatli-ip66-kombinasyon-bd2m6130-1020-x": {"metaTitle":"Otomatlı IP66 Kombinasyon 5/32A · 1/16A","metaDescription":"Şarj ünitesi ekipmanı: IP66 otomatlı kombinasyon ünitesi, 5/32A · 1/16A ön. Toz ve su jetine karşı tam koruma, dış mekana uygun · yerli üretim · CE · IP66. Üreticisinden teklif","focusKeyword":"otomatlı ip66 kombinasyon","keywords":"otomatlı ip66 kombinasyon, ip66 kombinasyon ünitesi 5/32a, dış mekan şarj kombinasyon, şarj koruma dağıtım, şarj ünitesi ekipmanı, yerli, bemis"},
  "otomatli-ip66-kombinasyon-bd2m6130-1191-x": {"metaTitle":"Otomatlı IP66 Kombinasyon 5/32A · 3/32A 220V","metaDescription":"Şarj ünitesi ekipmanı: IP66 otomatlı kombinasyon ünitesi, 5/32A · 3/32A 220V · 1/16A. Toz ve su jetine karşı tam koruma, dış mekana uygun · yerli üretim · CE · IP66. Üreticisinden","focusKeyword":"otomatlı ip66 kombinasyon","keywords":"otomatlı ip66 kombinasyon, ip66 kombinasyon ünitesi 220v, dış mekan şarj kombinasyon, şarj koruma dağıtım, şarj ünitesi ekipmanı, yerli, bemis"},
  "dc-sarj-soketi-ccs2-bir-ucu-acik-150a-5m": {"metaTitle":"DC Şarj Soketi CCS2 Bir Ucu Açık 150A 5m","metaDescription":"Şarj ünitesi ekipmanı: bir ucu açık CCS2 DC şarj soketi, 150A 5m. DC hızlı şarj ünitelerine doğrudan terminasyon · yerli üretim · CE · IP65. OEM çözüm. Üreticisinden teklif alın.","focusKeyword":"ccs2 dc şarj soketi","keywords":"ccs2 dc şarj soketi, bir ucu açık ccs2 soket, dc hızlı şarj soketi 150a, oem dc soket, şarj ünitesi ekipmanı, yerli, bemis"},
  "dc-sarj-soketi-ccs2-bir-ucu-acik-150a-8m": {"metaTitle":"DC Şarj Soketi CCS2 Bir Ucu Açık 150A 8m","metaDescription":"Şarj ünitesi ekipmanı: bir ucu açık CCS2 DC şarj soketi, 150A 8m. DC hızlı şarj ünitelerine doğrudan terminasyon · yerli üretim · CE · IP65. OEM çözüm. Üreticisinden teklif alın.","focusKeyword":"ccs2 dc şarj soketi","keywords":"ccs2 dc şarj soketi, bir ucu açık ccs2 soket, dc hızlı şarj soketi 150a, 8m dc soket, şarj ünitesi ekipmanı, yerli, bemis"},
  "dc-sarj-soketi-ccs2-bir-ucu-acik-250a-5m": {"metaTitle":"DC Şarj Soketi CCS2 Bir Ucu Açık 250A 5m","metaDescription":"Şarj ünitesi ekipmanı: bir ucu açık CCS2 DC şarj soketi, 250A 5m. DC hızlı şarj ünitelerine doğrudan terminasyon · yerli üretim · CE · IP65. OEM çözüm. Üreticisinden teklif alın.","focusKeyword":"ccs2 dc şarj soketi","keywords":"ccs2 dc şarj soketi, bir ucu açık ccs2 soket, dc hızlı şarj soketi 250a, oem dc soket, şarj ünitesi ekipmanı, yerli, bemis"},
  "dc-sarj-soketi-ccs2-bir-ucu-acik-250a-8m": {"metaTitle":"DC Şarj Soketi CCS2 Bir Ucu Açık 250A 8m","metaDescription":"Şarj ünitesi ekipmanı: bir ucu açık CCS2 DC şarj soketi, 250A 8m. DC hızlı şarj ünitelerine doğrudan terminasyon · yerli üretim · CE · IP65. OEM çözüm. Üreticisinden teklif alın.","focusKeyword":"ccs2 dc şarj soketi","keywords":"ccs2 dc şarj soketi, bir ucu açık ccs2 soket, dc hızlı şarj soketi 250a, 8m dc soket, şarj ünitesi ekipmanı, yerli, bemis"},
  "dc-sarj-soketi-ccs2-bir-ucu-acik-400a-5m": {"metaTitle":"DC Şarj Soketi CCS2 Bir Ucu Açık 400A 5m","metaDescription":"Şarj ünitesi ekipmanı: bir ucu açık CCS2 DC şarj soketi, 400A 5m. DC hızlı şarj ünitelerine doğrudan terminasyon · yerli üretim · CE · IP65. OEM çözüm. Üreticisinden teklif alın.","focusKeyword":"ccs2 dc şarj soketi","keywords":"ccs2 dc şarj soketi, bir ucu açık ccs2 soket, dc hızlı şarj soketi 400a, oem dc soket, şarj ünitesi ekipmanı, yerli, bemis"},
  "dc-sarj-soketi-ccs2-bir-ucu-acik-400a-8m": {"metaTitle":"DC Şarj Soketi CCS2 Bir Ucu Açık 400A 8m","metaDescription":"Şarj ünitesi ekipmanı: bir ucu açık CCS2 DC şarj soketi, 400A 8m. DC hızlı şarj ünitelerine doğrudan terminasyon · yerli üretim · CE · IP65. OEM çözüm. Üreticisinden teklif alın.","focusKeyword":"ccs2 dc şarj soketi","keywords":"ccs2 dc şarj soketi, bir ucu açık ccs2 soket, dc hızlı şarj soketi 400a, 8m dc soket, şarj ünitesi ekipmanı, yerli, bemis"},
};

function pick(a: string | undefined, b: string | undefined): string | undefined {
  return a && a.trim() ? a : b;
}

// Kategorilerdeki ürünlere SEO varsayılanlarını DOLDURUR (yeni nesneler döndürür —
// cache'lenmiş Blob nesnelerini DEĞİŞTİRMEZ). Üründe zaten değer varsa o korunur.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export function applyProductSeo<T extends { products?: any[] }>(cats: T[]): T[] {
  if (!Array.isArray(cats)) return cats;
  return cats.map((cat) => {
    if (!cat || !Array.isArray(cat.products)) return cat;
    return {
      ...cat,
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      products: cat.products.map((p: any) => {
        const seo = p && p.id ? PRODUCT_SEO[p.id] : undefined;
        if (!seo) return p;
        return {
          ...p,
          metaTitle: pick(p.metaTitle, seo.metaTitle),
          metaDescription: pick(p.metaDescription, seo.metaDescription),
          focusKeyword: pick(p.focusKeyword, seo.focusKeyword),
          keywords: pick(p.keywords, seo.keywords),
        };
      }),
    };
  });
}
