#!/usr/bin/env node
/**
 * Bridge between CI agents and notification surfaces.
 *
 * Reads a finding from stdin (JSON) and:
 *   1. Opens / updates a GitHub Issue (idempotent — same title gets
 *      a new comment, not a duplicate issue).
 *   2. Sends an email to NOTIFY_EMAIL via Resend.
 *
 * The agent workflow pipes its summary into this script:
 *
 *   echo '{"title":"...","severity":"critical|medium|low","body":"..."}' \
 *     | node scripts/notify-finding.cjs
 *
 * Env vars (all required in CI):
 *   GH_TOKEN           — github-actions[bot] token, scope: issues:write
 *   GH_REPO            — owner/name, e.g. bemis2026/Bemis-Server
 *   RESEND_API_KEY     — same key Vercel uses for the contact form
 *   RESEND_FROM_EMAIL  — noreply@bemisevcharge.com once DNS is verified
 *   NOTIFY_EMAIL       — info@bemisevcharge.com (operator inbox)
 *
 * Safe to skip mail when RESEND_API_KEY isn't set (e.g. local test).
 */

const TITLE_PREFIX = "[Auto] ";

function readStdin() {
  return new Promise((resolve, reject) => {
    let buf = "";
    process.stdin.setEncoding("utf8");
    process.stdin.on("data", (c) => (buf += c));
    process.stdin.on("end", () => resolve(buf));
    process.stdin.on("error", reject);
  });
}

const SEVERITY_LABEL = {
  critical: "🔴 KRİTİK",
  medium:   "🟡 ORTA",
  low:      "🟢 BİLGİ",
};

async function ghFetch(path, init) {
  const token = process.env.GH_TOKEN;
  const repo = process.env.GH_REPO;
  if (!token || !repo) throw new Error("GH_TOKEN / GH_REPO env vars missing");
  const res = await fetch(`https://api.github.com/repos/${repo}${path}`, {
    ...init,
    headers: {
      Accept: "application/vnd.github+json",
      Authorization: `Bearer ${token}`,
      "X-GitHub-Api-Version": "2022-11-28",
      ...(init?.headers ?? {}),
    },
  });
  if (!res.ok) {
    const t = await res.text();
    throw new Error(`GitHub ${res.status}: ${t}`);
  }
  return res.json();
}

async function findOrCreateIssue(title, body, labels) {
  const repo = process.env.GH_REPO;
  // Search open issues with matching title (idempotency key).
  const q = encodeURIComponent(`repo:${repo} state:open in:title "${title}"`);
  const search = await fetch(`https://api.github.com/search/issues?q=${q}`, {
    headers: {
      Accept: "application/vnd.github+json",
      Authorization: `Bearer ${process.env.GH_TOKEN}`,
    },
  }).then((r) => r.json());
  const existing = (search.items ?? []).find((i) => i.title === title);
  if (existing) {
    // Append a comment instead of opening a duplicate.
    await ghFetch(`/issues/${existing.number}/comments`, {
      method: "POST",
      body: JSON.stringify({ body }),
    });
    return { number: existing.number, action: "comment" };
  }
  const created = await ghFetch(`/issues`, {
    method: "POST",
    body: JSON.stringify({ title, body, labels: labels ?? [] }),
  });
  return { number: created.number, action: "create" };
}

async function sendMail(subject, html) {
  const key = process.env.RESEND_API_KEY;
  const from = process.env.RESEND_FROM_EMAIL || "Bemis Bot <onboarding@resend.dev>";
  const to = process.env.NOTIFY_EMAIL;
  if (!key || !to) {
    console.log("[notify] mail skipped — RESEND_API_KEY or NOTIFY_EMAIL missing");
    return;
  }
  const res = await fetch("https://api.resend.com/emails", {
    method: "POST",
    headers: { "Content-Type": "application/json", Authorization: `Bearer ${key}` },
    body: JSON.stringify({ from, to: [to], subject, html, reply_to: to }),
  });
  if (!res.ok) console.error("[notify] mail failed:", await res.text());
}

(async () => {
  const raw = await readStdin();
  let finding;
  try {
    finding = JSON.parse(raw);
  } catch {
    console.error("notify-finding: invalid JSON on stdin");
    process.exit(2);
  }
  const severity = String(finding.severity ?? "medium").toLowerCase();
  const label = SEVERITY_LABEL[severity] ?? SEVERITY_LABEL.medium;
  const title = `${TITLE_PREFIX}${finding.title}`;
  const body =
    `${label}\n\n${finding.body || ""}\n\n_Generated by ${finding.source || "bemis-bot"} at ` +
    new Date().toISOString() + `_`;

  try {
    const issue = await findOrCreateIssue(title, body, [
      "auto",
      `severity:${severity}`,
      ...(finding.source ? [`source:${finding.source}`] : []),
    ]);
    console.log(`[notify] github issue #${issue.number} (${issue.action})`);
  } catch (e) {
    console.error("[notify] github failed:", e.message);
  }

  try {
    await sendMail(
      `[Bemis Site] ${label} — ${finding.title}`,
      `<div style="font-family:Arial,sans-serif;color:#111;line-height:1.6">
        <h2 style="margin:0 0 12px;font-size:18px">${label}</h2>
        <h3 style="margin:0 0 16px;font-size:15px;color:#444">${escapeHtml(finding.title)}</h3>
        <pre style="background:#f5f5f5;padding:14px;border-radius:8px;font-size:12px;white-space:pre-wrap">${escapeHtml(finding.body || "")}</pre>
        <p style="font-size:11px;color:#888;margin-top:16px">Source: ${escapeHtml(finding.source || "n/a")} · ${new Date().toISOString()}</p>
      </div>`
    );
  } catch (e) {
    console.error("[notify] mail failed:", e.message);
  }
})();

function escapeHtml(s) {
  return String(s ?? "").replace(/[&<>"']/g, (c) => ({
    "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#039;",
  }[c]));
}
